---
- hosts: all

  vars:
    ship_name: "Bessie"
    ship_type: "Intergalactic"
    engines: "Dark Matter"
    dark_Matter_balls: 63
    ship_price_in_beans: 2

  tasks:
  - name: Configure space config file
    template:
      src: /root/playbooks/templates/ship.cfg.j2
      dest: ~/ship.cfg
